In [1]:
import pandas as pd

In [2]:
#intitial exploration
#identify some columns that may require cleaning e.g. photoUrl, playerUrl and Team & Contract. These are just a few examples. 
df = pd.read_csv("fifa21_raw_data.csv")

df.head()

C:\Users\amyna\AppData\Local\Temp\ipykernel_20820\134512170.py:3: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("fifa21_raw_data.csv")

,photoUrl,LongName,playerUrl,Nationality,Positions,Name,Age,↓OVA,POT,Team & Contract,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,https://cdn.sofifa.com/players/158/023/21_60.png,Lionel Messi,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,https://cdn.sofifa.com/players/020/801/21_60.png,C. Ronaldo dos Santos Aveiro,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,https://cdn.sofifa.com/players/200/389/21_60.png,Jan Oblak,http://sofifa.com/player/200389/jan-oblak/210005/,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,https://cdn.sofifa.com/players/192/985/21_60.png,Kevin De Bruyne,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,...,High,High,4 ★,76,86,93,88,64,78,\n163
4,https://cdn.sofifa.com/players/190/871/21_60.png,Neymar da Silva Santos Jr.,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [3]:
#rename columns that don't have appropriate names
df.columns

Index(['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name',
       'Age', '↓OVA', 'POT', 'Team & Contract', 'ID', 'Height', 'Weight',
       'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End', 'Value',
       'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [4]:
df.rename(columns = {'↓OVA': 'Overall Rating'}, inplace = True)

In [5]:
df.columns

Index(['photoUrl', 'LongName', 'playerUrl', 'Nationality', 'Positions', 'Name',
       'Age', 'Overall Rating', 'POT', 'Team & Contract', 'ID', 'Height',
       'Weight', 'foot', 'BOV', 'BP', 'Growth', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='object')

In [6]:
pd.set_option('display.max_rows', None) # this will make sure none of the column names are skipped. Try running the code without this statement.
df.isnull().sum()

photoUrl                0
LongName                0
playerUrl               0
Nationality             0
Positions               0
Name                    0
Age                     0
Overall Rating          0
POT                     0
Team & Contract         0
ID                      0
Height                  0
Weight                  0
foot                    0
BOV                     0
BP                      0
Growth                  0
Joined                  0
Loan Date End       17966
Value                   0
Wage                    0
Release Clause          0
Attacking               0
Crossing                0
Finishing               0
Heading Accuracy        0
Short Passing           0
Volleys                 0
Skill                   0
Dribbling               0
Curve                   0
FK Accuracy             0
Long Passing            0
Ball Control            0
Movement                0
Acceleration            0
Sprint Speed            0
Agility                 0
Reactions               0
Balance                 0
Power                   0
Shot Power              0
Jumping                 0
Stamina                 0
Strength                0
Long Shots              0
Mentality               0
Aggression              0
Interceptions           0
Positioning             0
Vision                  0
Penalties               0
Composure               0
Defending               0
Marking                 0
Standing Tackle         0
Sliding Tackle          0
Goalkeeping             0
GK Diving               0
GK Handling             0
GK Kicking              0
GK Positioning          0
GK Reflexes             0
Total Stats             0
Base Stats              0
W/F                     0
SM                      0
A/W                     0
D/W                     0
IR                      0
PAC                     0
SHO                     0
PAS                     0
DRI                     0
DEF                     0
PHY                     0
Hits                    0
dtype: int64

In [7]:
df['Loan Date End'].unique()

array([nan, 'Jun 30, 2021', 'Dec 31, 2020', 'Jan 30, 2021',
       'Jun 30, 2022', 'May 31, 2021', 'Jul 5, 2021', 'Dec 31, 2021',
       'Jul 1, 2021', 'Jan 1, 2021', 'Aug 31, 2021', 'Jan 31, 2021',
       'Dec 30, 2021', 'Jun 23, 2021', 'Jan 3, 2021', 'Nov 27, 2021',
       'Jan 17, 2021', 'Jun 30, 2023', 'Jul 31, 2021', 'Nov 22, 2020',
       'May 31, 2022', 'Dec 30, 2020', 'Jan 4, 2021', 'Nov 30, 2020',
       'Aug 1, 2021'], dtype=object)

In [8]:
#replace blank values with something more intuitive e.g. "No Loan" or "No end date"
df = df.fillna('No Loan')

In [9]:
#double check if the code ran successfully
df['Loan Date End'].value_counts()

Loan Date End
No Loan         17966
Jun 30, 2021      770
Dec 31, 2020      100
May 31, 2021       30
Dec 31, 2021       22
Jan 31, 2021       18
Jan 1, 2021        15
Jun 30, 2022       15
Nov 30, 2020        7
Jun 23, 2021        7
Nov 27, 2021        6
Nov 22, 2020        5
Jan 3, 2021         3
Jan 4, 2021         2
Aug 31, 2021        2
May 31, 2022        2
Dec 30, 2020        1
Jul 31, 2021        1
Dec 30, 2021        1
Jun 30, 2023        1
Jan 17, 2021        1
Jul 1, 2021         1
Jul 5, 2021         1
Jan 30, 2021        1
Aug 1, 2021         1
Name: count, dtype: int64

In [10]:
# drop photoUrl and playerUrl columns and then double check if it worked
df = df.drop('playerUrl', axis=1)
df = df.drop('photoUrl', axis=1)

df.head()

,LongName,Nationality,Positions,Name,Age,Overall Rating,POT,Team & Contract,ID,Height,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,158023,"5'7""",...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,20801,"6'2""",...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,200389,"6'2""",...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,192985,"5'11""",...,High,High,4 ★,76,86,93,88,64,78,\n163
4,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,190871,"5'9""",...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [11]:
#Move the ID column up
id_column = df['ID']

df.drop(columns=['ID'], inplace=True)

df.insert(0, 'ID', id_column)
df.head()

,ID,LongName,Nationality,Positions,Name,Age,Overall Rating,POT,Team & Contract,Height,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,"5'7""",...,Medium,Low,5 ★,85,92,91,95,38,65,\n372
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,"6'2""",...,High,Low,5 ★,89,93,81,89,35,77,\n344
2,200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,"6'2""",...,Medium,Medium,3 ★,87,92,78,90,52,90,\n86
3,192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,"5'11""",...,High,High,4 ★,76,86,93,88,64,78,\n163
4,190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,"5'9""",...,High,Medium,5 ★,91,85,86,94,36,59,\n273

In [15]:
#you can either use .map with a dictionary or define a function and then use .apply. Both are valid approaches. 
#repear rhe same for D/W score

score_to_points = {'Low': 1, 'Medium': 2, 'High': 3}

df['A/W Score'] = df['A/W'].map(score_to_points)

df.head()

,ID,LongName,Nationality,Positions,Name,Age,Overall Rating,POT,Team & Contract,Height,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,A/W Score
0,158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,\n\n\n\nFC Barcelona\n2004 ~ 2021\n\n,"5'7""",...,Low,5 ★,85,92,91,95,38,65,\n372,2
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,\n\n\n\nJuventus\n2018 ~ 2022\n\n,"6'2""",...,Low,5 ★,89,93,81,89,35,77,\n344,3
2,200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,\n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n,"6'2""",...,Medium,3 ★,87,92,78,90,52,90,\n86,2
3,192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,\n\n\n\nManchester City\n2015 ~ 2023\n\n,"5'11""",...,High,4 ★,76,86,93,88,64,78,\n163,3
4,190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,\n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n,"5'9""",...,Medium,5 ★,91,85,86,94,36,59,\n273,3

In [ ]:
#remove the the 'lbs' from the end of the weight column
df['Weight'] = df['Weight'].str[:-3]
df['Weight'] = pd.to_numeric(df['Weight'])


df.head()

In [29]:
# we will analyze the age column for outliers

df['Age'].value_counts()

Age
23    1464
24    1426
22    1421
20    1408
21    1381
26    1287
28    1271
25    1239
27    1213
19    1076
29    1045
30     929
31     768
18     697
32     629
33     473
34     357
17     289
35     220
36     161
37      80
38      56
16      35
39      27
40      13
41       6
42       5
43       2
53       1
Name: count, dtype: int64

In [36]:
# we will use a boolean mask to remove age outliers
df = df[(df['Age'] >= 19) & (df['Age'] < 40)]
df['Age'].value_counts().sort_index()

Age
19    1076
20    1408
21    1381
22    1421
23    1464
24    1426
25    1239
26    1287
27    1213
28    1271
29    1045
30     929
31     768
32     629
33     473
34     357
35     220
36     161
37      80
38      56
39      27
Name: count, dtype: int64

In [ ]:
df['Value'] = df['Value'].str[1:]

In [ ]:
df['Value'].head()

In [16]:
#extract the last character to see if they are all in million or if there are others too
last_chars = df['Value'].str[-1]

print(last_chars.value_counts())

Value
K    11944
M     6786
0      249
Name: count, dtype: int64

In [ ]:
# for q.9 one option is to define a function and then use .apply
def convert_to_numeric(value):
    if value.endswith('M'):
        return float(value[:-1]) * 1000000
    elif value.endswith('K'):
        return float(value[:-1]) * 1000
    else:
        return float(value)
    
df['Value'] = df['Value'].apply(lambda x: convert_to_numeric(x))

In [ ]:
df['Value'].head()

In [ ]:
# another option for q.9 is to use .where from the numpy library
import numpy as np
# Convert 'M' values to numeric
df['Value'] = np.where(df['Value'].str.endswith('M'), 
                       df['Value'].str[:-1].astype(float) * 1000000, 
                       df['Value'])

# Convert 'K' values to numeric
df['Value'] = np.where(df['Value'].str.endswith('K'), 
                       df['Value'].str[:-1].astype(float) * 1000, 
                       df['Value'])

# Convert remaining values to numeric
df['Value'] = df['Value'].astype(float)

In [37]:
df['Team & Contract'].head()

0           \n\n\n\nFC Barcelona\n2004 ~ 2021\n\n
1               \n\n\n\nJuventus\n2018 ~ 2022\n\n
2        \n\n\n\nAtlético Madrid\n2014 ~ 2023\n\n
3        \n\n\n\nManchester City\n2015 ~ 2023\n\n
4    \n\n\n\nParis Saint-Germain\n2017 ~ 2022\n\n
Name: Team & Contract, dtype: object

In [38]:
df['Team & Contract'] = df['Team & Contract'].str.replace('\n','')

df.head()

,ID,LongName,Nationality,Positions,Name,Age,Overall Rating,POT,Team & Contract,Height,...,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits,A/W Score
0,158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona2004 ~ 2021,"5'7""",...,Low,5 ★,85,92,91,95,38,65,\n372,2
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus2018 ~ 2022,"6'2""",...,Low,5 ★,89,93,81,89,35,77,\n344,3
2,200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid2014 ~ 2023,"6'2""",...,Medium,3 ★,87,92,78,90,52,90,\n86,2
3,192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City2015 ~ 2023,"5'11""",...,High,4 ★,76,86,93,88,64,78,\n163,3
4,190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain2017 ~ 2022,"5'9""",...,Medium,5 ★,91,85,86,94,36,59,\n273,3

In [39]:
#first we are extracting the End Year
df[['Team', 'End Contract']] = df['Team & Contract'].str.split(' ~ ', expand=True)
df.head()

,ID,LongName,Nationality,Positions,Name,Age,Overall Rating,POT,Team & Contract,Height,...,PAC,SHO,PAS,DRI,DEF,PHY,Hits,A/W Score,Team,End Contract
0,158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona2004 ~ 2021,"5'7""",...,85,92,91,95,38,65,\n372,2,FC Barcelona2004,2021
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus2018 ~ 2022,"6'2""",...,89,93,81,89,35,77,\n344,3,Juventus2018,2022
2,200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid2014 ~ 2023,"6'2""",...,87,92,78,90,52,90,\n86,2,Atlético Madrid2014,2023
3,192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City2015 ~ 2023,"5'11""",...,76,86,93,88,64,78,\n163,3,Manchester City2015,2023
4,190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain2017 ~ 2022,"5'9""",...,91,85,86,94,36,59,\n273,3,Paris Saint-Germain2017,2022

In [40]:
df['Start Year'] = df['Team'].str[-4:]
df['Team'] = df['Team'].str[:-4]

df.head()

,ID,LongName,Nationality,Positions,Name,Age,Overall Rating,POT,Team & Contract,Height,...,SHO,PAS,DRI,DEF,PHY,Hits,A/W Score,Team,End Contract,Start Year
0,158023,Lionel Messi,Argentina,RW ST CF,L. Messi,33,93,93,FC Barcelona2004 ~ 2021,"5'7""",...,92,91,95,38,65,\n372,2,FC Barcelona,2021,2004
1,20801,C. Ronaldo dos Santos Aveiro,Portugal,ST LW,Cristiano Ronaldo,35,92,92,Juventus2018 ~ 2022,"6'2""",...,93,81,89,35,77,\n344,3,Juventus,2022,2018
2,200389,Jan Oblak,Slovenia,GK,J. Oblak,27,91,93,Atlético Madrid2014 ~ 2023,"6'2""",...,92,78,90,52,90,\n86,2,Atlético Madrid,2023,2014
3,192985,Kevin De Bruyne,Belgium,CAM CM,K. De Bruyne,29,91,91,Manchester City2015 ~ 2023,"5'11""",...,86,93,88,64,78,\n163,3,Manchester City,2023,2015
4,190871,Neymar da Silva Santos Jr.,Brazil,LW CAM,Neymar Jr,28,91,91,Paris Saint-Germain2017 ~ 2022,"5'9""",...,85,86,94,36,59,\n273,3,Paris Saint-Germain,2022,2017